[package]
name = "gameboy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "desktop"
path = "src/desktop.rs"

[lib]
name = "web"
path = "src/web.rs"
crate-type = ["cdylib"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = { version = "0.28.0" }
gl = { version = "0.14.0" }
libc = { version = "0.2.126" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.59"
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.32"
console_error_panic_hook = "0.1.7"
web-sys = {version = "0.3.4", features = [
  'Document',
  'Element',
  'HtmlCanvasElement',
  'CanvasRenderingContext2d',
  'ImageData',
  'Window',
  'KeyboardEvent',
]}

[profile.release]
opt-level = "s"
lto = "thin"
strip = true
debug = 0
panic = "abort"
codegen-units = 1
incremental = false

[profile.dev]
split-debuginfo = "unpacked"
lto = false
incremental = true
opt-level = 0
